### ISSUE TITLE
Deploy without name key in package.json breaks code

### ISSUE THREAD

**Issue by lucasfcnunes** [hiro5id/console-log-json#50]
We use nx for monorepo management so in production, our package.json doesn't have the "name" key thus `packageName` is undefined.
```log
TypeError: Cannot read properties of undefined (reading 'length')
    at logUsingWinston (/app/node_modules/console-log-json/src/logger.ts:401:19)
    at console.LoggerAdaptToConsole.console.error (/app/node_modules/console-log-json/src/logger.ts:315:12)
    at printErrorAndExit (/app/node_modules/source-map-support/source-map-support.js:499:11)
    at process.emit (/app/node_modules/source-map-support/source-map-support.js:512:16)
    at process._fatalException (node:internal/process/execution:167:25)
{"level":"error","message":"Forever detected script exited with code: 7"}
{"level":"error","message":"Script restart attempt #225"}
/app/node_modules/console-log-json/dist/src/logger.js:339
    if (packageName.length === 0) {
```

**Comment by hiro5id** [comment]
Thank you so much for the contribution @lucasfcnunes i will merge and publish

**Comment by hiro5id** [comment]
published.... although, I'm a bit miffed at why the [NPM page](https://www.npmjs.com/package/console-log-json) is not showing the readme even though it is there in the package... i'll have to chase that up with NPM and see..
